Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -1,61 +1,44 @@
-name: Checkov and Terraform
+name: Terraform Checkov and Apply
 
 on:
   push:
     branches:
-      - master
+      - master  # You can specify the branch you want to trigger this workflow on
 
 jobs:
-  build:
+  checkov:
     runs-on: ubuntu-latest
+
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
 
-      - name: Set up Python 3.8
-        uses: actions/setup-python@v4
-        with:
-          python-version: 3.8
-
       - name: Install Checkov
-        run: pip3 install checkov 
+        run: |
+          pip install --user checkov
+          echo "$HOME/.local/bin" >> $GITHUB_PATH
 
-      - name: Check Terraform with Checkov
-        run: checkov -d ./Compute-Engine
-        
-      - name: Check Terraform with Checkov Success
-        run: echo "Checkov completed successfully."
+      - name: Run Checkov
+        id: checkov
+        run: |
+          checkov -d ./Compute-Engine || echo "Checkov found errors"
+        continue-on-error: true
 
-      - name: Send Failure Notification
-        if: failure()
-        run: echo "The 'build' job failed."
-
-
-
-  terraform-job2:
+  apply:
+    needs: checkov
     runs-on: ubuntu-latest
-    needs: build
-    # if: failure()
+    if: ${{ !always() && success() }}  # Only run if the 'checkov' job succeeded
+
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
 
       - name: Set up Terraform
         uses: hashicorp/setup-terraform@v1
-        with:
-          terraform_version: 1.0.3   # Specify the desired Terraform version
 
       - name: Terraform Init
         run: terraform init
-      
-      - name: Terraform Format
-        run: terraform fmt
-      
-      - name: Terraform Validation
-        run: terraform validate
-      
-      - name: Terraform Plan
+
+      - name: Terraform Apply
         run: terraform plan
 
-      - name: Terraform plan
-        run: terraform plan
